In [1]:
w1, w2, w3 = 0.3, 0.2, 0.5

In [2]:
kanto_temp = 73
kanto_rainfall = 67
kanto_humidity = 43

In [3]:
kanto_yield_apples = kanto_temp * w1 + kanto_rainfall * w2 + kanto_humidity * w3

In [4]:
print(f"The expected yield of apples in kanto region is {kanto_yield_apples} tons per hectare")

The expected yield of apples in kanto region is 56.8 tons per hectare


In [5]:
kanto = [73, 67, 43]
johto = [91, 88 ,64]
hoenn = [87, 134, 58]
sinnoh = [102, 43, 37]
unova = [69, 96, 70]

In [6]:
weights = [w1, w2, w3]

In [7]:
weights

[0.3, 0.2, 0.5]

In [8]:
def crop_yield(region, weights):
    result = 0
    for x, w in zip(region, weights):
        result += x * w
    return result
# zip just groups together corresponding elements of the arguments
# It can have more than two arguments

In [9]:
crop_yield(kanto, weights)

56.8

In [10]:
crop_yield(johto, weights)

76.9

In [11]:
crop_yield(hoenn, weights)

81.9

In [12]:
import numpy as np

In [13]:
kanto = np.array([73, 67, 43])

In [14]:
kanto

array([73, 67, 43])

In [15]:
weights = np.array([w1, w2, w3])

In [16]:
weights

array([0.3, 0.2, 0.5])

In [17]:
type(weights)
# Type of weights is no longer a normal array, it's "ndarray" which is
# a data structure of numpy library

numpy.ndarray

In [18]:
# Python lists
arr1 = list(range(1000000))
arr2 = list(range(1000000,2000000))

# Numpy arrays
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

In [19]:
%%time
# %%time gives the time taken to run the respective block of code
result = 0
for x1, x2 in zip(arr1, arr2):
    result += x1 * x2
result

CPU times: user 164 ms, sys: 2.19 ms, total: 166 ms
Wall time: 165 ms


833332333333500000

In [20]:
%%time
np.dot(arr1_np, arr2_np)

CPU times: user 2.74 ms, sys: 1.01 ms, total: 3.76 ms
Wall time: 2.19 ms


833332333333500000

In [21]:
# Multi-dimensional arrays
# Data of 5 cities
climate_data = np.array([[73, 67, 43],
                         [91, 88, 64],
                         [87, 134, 58],
                         [102, 43, 37],
                         [69, 96, 70]]) 

In [22]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [23]:
# 2-D array / matrix
climate_data.shape

(5, 3)

In [24]:
weights

array([0.3, 0.2, 0.5])

In [25]:
weights.shape

(3,)

In [26]:
# 3-D array
arr3 = np.array([
    [
        [11, 12, 13], [13, 14, 15]
    ],
    [
        [15, 16, 17],[17, 18, 19.5]
    ]
])

In [27]:
arr3

array([[[11. , 12. , 13. ],
        [13. , 14. , 15. ]],

       [[15. , 16. , 17. ],
        [17. , 18. , 19.5]]])

In [28]:
arr3.shape

(2, 2, 3)

In [29]:
weights.dtype

dtype('float64')

In [30]:
# Since 19.5 is given in the array which is a float, all other values
# are converted to data type float
climate_data.dtype

dtype('int64')

In [31]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [32]:
weights

array([0.3, 0.2, 0.5])

In [33]:
# np.matmul is used for matrix multiplication
np.matmul(climate_data, weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [34]:
# @ can also be used for matrix multiplication
climate_data @ weights

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [35]:
# Retrieving or downloading a file from a url into file "climate.txt"
import urllib.request

urllib.request.urlretrieve(
    'https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv', 
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x7fdf1f0a5070>)

In [36]:
# Loading the data from file into climate.txt
# delimiter = ',' says the values are separated by ','
# skip_header = 1 skips 1 line from the top while taking data
climate_data = np.genfromtxt('climate.txt', delimiter=',', skip_header=1)

In [37]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [38]:
climate_data.shape

(10000, 3)

In [39]:
weights

array([0.3, 0.2, 0.5])

In [40]:
yields = climate_data @ weights

In [41]:
yields

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [42]:
yields.shape

(10000,)

In [43]:
# yields.reshape(10000,1) changes the vector to a 10000,1 matrix
# axis = 1 means we want to add along the column
# row is 0th dimension, column is 1st dimension
climate_results = np.concatenate((climate_data, yields.reshape(10000, 1)), axis=1)

In [44]:
climate_results

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [45]:
np.savetxt('climate_results.txt', # saves to filename climate_results.txt
           climate_results, # climate_results array is saved as data
           fmt = '%.2f', #terminates data to 2 decimals
           header = 'temperature, rainfall, humidity, yield_apples',
#            adds a header with titles of variables
           comments = '')

In [46]:
# Arithmetic operations
arr2 = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 1, 2, 3]])
arr3 = np.array([[11, 12, 13, 14], 
                 [15, 16, 17, 18], 
                 [19, 11, 12, 13]])

In [47]:
# Adding a scalar
arr2 + 3

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12,  4,  5,  6]])

In [48]:
arr3 - arr2

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [49]:
arr2 / 2

array([[0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. ],
       [4.5, 0.5, 1. , 1.5]])

In [50]:
arr2 * arr3

array([[ 11,  24,  39,  56],
       [ 75,  96, 119, 144],
       [171,  11,  24,  39]])

In [51]:
arr2 % 4

array([[1, 2, 3, 0],
       [1, 2, 3, 0],
       [1, 1, 2, 3]])

In [52]:
# Array broadcasting
# When two arrays are not of same dimensions but compatible shapes
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 1, 2, 3]])

In [53]:
arr2.shape

(3, 4)

In [54]:
arr4 = np.array([4, 5,  6, 7])

In [55]:
arr4.shape

(4,)

In [56]:
arr2 + arr4
# arr4 is added as a row to all three rows of arr2

array([[ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13,  6,  8, 10]])

In [57]:
arrC = np.array([[4],[5],[6]])

In [58]:
arrC.shape

(3, 1)

In [59]:
arr2 + arrC
# arrC is added as a column to all the four columns of arr2

array([[ 5,  6,  7,  8],
       [10, 11, 12, 13],
       [15,  7,  8,  9]])

In [60]:
# Corresponding elements of arrays can be compared
# It results in an array of booleans
arr1 = np.array([[1, 2, 3], [3, 4, 5]])
arr2 = np.array([[2, 2, 3], [1, 2, 5]])

In [61]:
arr1 == arr2

array([[False,  True,  True],
       [False, False,  True]])

In [62]:
arr1 != arr2

array([[ True, False, False],
       [ True,  True, False]])

In [63]:
arr1 >= arr2

array([[False,  True,  True],
       [ True,  True,  True]])

In [64]:
arr1 <= arr2

array([[ True,  True,  True],
       [False, False,  True]])

In [65]:
# sum() returns sum of elements of array
# For a boolean array it is number of true statements as true evaluates to 1
(arr1 == arr2).sum()

3

In [66]:
arr1.sum()

18

In [67]:
arr3 = np.array([
    [[11, 12, 13, 14], 
     [13, 14, 15, 19]], 
    
    [[15, 16, 17, 21], 
     [63, 92, 36, 18]], 
    
    [[98, 32, 81, 23],      
     [17, 18, 19.5, 43]]])

In [68]:
arr3.shape

(3, 2, 4)

In [69]:
# Single element
arr3[1, 1, 2]

36.0

In [71]:
# Subarray using ranges
# Note that the end number is open, i.e. not included, i.e.
# 0:1 means ony 0th is included
arr3[1:, 0:1, :2]

array([[[15., 16.]],

       [[98., 32.]]])

In [72]:
# Mixing indices and ranges
arr3[1:, 1, 3]

array([18., 43.])

In [73]:
# Mixing indices and ranges
arr3[1:, 1, :3]

array([[63. , 92. , 36. ],
       [17. , 18. , 19.5]])

In [74]:
# Using fewer indices
arr3[1]

array([[15., 16., 17., 21.],
       [63., 92., 36., 18.]])

In [75]:
# Using fewer indices
arr3[:2, 1]

array([[13., 14., 15., 19.],
       [63., 92., 36., 18.]])

In [76]:
# Other ways of creating numpy arrays
# All zeros
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [77]:
# All ones
# np.ones([2, 2, 3])
np.ones((2, 2, 3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [78]:
# Both parantheses and square brackets can be used for dimensions
np.ones([2, 2, 3])

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [79]:
# Identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [81]:
# Random vector
np.random.rand(5)

array([0.55907576, 0.58793763, 0.8961036 , 0.50333995, 0.26990104])

In [83]:
# Random matrix
np.random.randn(2,3)
# rand:generates random numbers
# randn: generstes random numbers from gaussian distribution

array([[ 0.98899685, -1.07795732, -1.1564379 ],
       [-0.76227606, -0.91576666,  0.16365998]])

In [84]:
# Matrix with same fixed value as entries
np.full([2, 3], 21)

array([[21, 21, 21],
       [21, 21, 21]])

In [85]:
# Range with start, end and step
np.arange(10, 90, 3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88])

In [86]:
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [87]:
# Equally spaced numbers in a range
np.linspace(3, 27, 18)

array([ 3.        ,  4.41176471,  5.82352941,  7.23529412,  8.64705882,
       10.05882353, 11.47058824, 12.88235294, 14.29411765, 15.70588235,
       17.11764706, 18.52941176, 19.94117647, 21.35294118, 22.76470588,
       24.17647059, 25.58823529, 27.        ])

In [88]:
np.linspace(3, 27, 9)

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.])